// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgxdwGNX8PBH9Y8d1_TMp2UNx_ZkwkGnI',
    appId: '1:196820978897:web:101085c2a9efcd615c49f0',
    messagingSenderId: '196820978897',
    projectId: 'mindcare-97d3b',
    authDomain: 'mindcare-97d3b.firebaseapp.com',
    databaseURL: 'https://mindcare-97d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindcare-97d3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmuh4oMggojCnmjRoJ2f5xo4hnWvO-d1M',
    appId: '1:196820978897:android:4e75a06cc37b4f515c49f0',
    messagingSenderId: '196820978897',
    projectId: 'mindcare-97d3b',
    databaseURL: 'https://mindcare-97d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindcare-97d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7GydKVfJLa_yMb8K_7S77ISMFrEzidWY',
    appId: '1:196820978897:ios:bd658b4ee5391b635c49f0',
    messagingSenderId: '196820978897',
    projectId: 'mindcare-97d3b',
    databaseURL: 'https://mindcare-97d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindcare-97d3b.firebasestorage.app',
    androidClientId: '196820978897-05usfqpl4oaqv5pgg476ku46v8lm2q0k.apps.googleusercontent.com',
    iosClientId: '196820978897-b1ps1nfvs2022efo9p8jvj0q7ollvuqc.apps.googleusercontent.com',
    iosBundleId: 'com.major.mindcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7GydKVfJLa_yMb8K_7S77ISMFrEzidWY',
    appId: '1:196820978897:ios:bd658b4ee5391b635c49f0',
    messagingSenderId: '196820978897',
    projectId: 'mindcare-97d3b',
    databaseURL: 'https://mindcare-97d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindcare-97d3b.firebasestorage.app',
    androidClientId: '196820978897-05usfqpl4oaqv5pgg476ku46v8lm2q0k.apps.googleusercontent.com',
    iosClientId: '196820978897-b1ps1nfvs2022efo9p8jvj0q7ollvuqc.apps.googleusercontent.com',
    iosBundleId: 'com.major.mindcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgxdwGNX8PBH9Y8d1_TMp2UNx_ZkwkGnI',
    appId: '1:196820978897:web:545112e28310f07b5c49f0',
    messagingSenderId: '196820978897',
    projectId: 'mindcare-97d3b',
    authDomain: 'mindcare-97d3b.firebaseapp.com',
    databaseURL: 'https://mindcare-97d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindcare-97d3b.firebasestorage.app',
  );
}
