name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: pod install
        working-directory: ios

      - name: Update Pods
        run: pod repo update
        working-directory: ios

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create Payload Folder
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlutterIpaExport
          path: build/ios/iphoneos/FlutterIpaExport.ipa